# Generated by Django 4.2 on 2024-09-29 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_file', models.FileField(upload_to='user_reports/')),
                ('submitted_at', models.DateField(auto_now_add=True)),
                ('doctor_name', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_report', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_collection', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hemoglobin', models.CharField(blank=True, max_length=50, null=True)),
                ('rbc_count', models.CharField(blank=True, max_length=50, null=True)),
                ('wbc_count', models.CharField(blank=True, max_length=50, null=True)),
                ('platelet_count', models.CharField(blank=True, max_length=50, null=True)),
                ('pcv', models.CharField(blank=True, max_length=50, null=True)),
                ('bilirubin', models.CharField(blank=True, max_length=50, null=True)),
                ('proteins', models.CharField(blank=True, max_length=50, null=True)),
                ('calcium', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_urea', models.CharField(blank=True, max_length=50, null=True)),
                ('report_data', models.JSONField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.report')),
            ],
        ),
    ]
