# Generated by Django 4.2 on 2024-10-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_reportdetail_sr_cholestrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
