# Generated by Django 4.2 on 2024-10-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_report_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_pic',
            field=models.FileField(default='profile_pics/default_pp.jpg', upload_to='profilepics/'),
        ),
    ]
