# Generated by Django 4.2 on 2024-10-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_patientprofile_phone_number_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
