# Generated by Django 4.2 on 2024-10-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_patientprofile_height_patientprofile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='profile_qr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
