# Generated by Django 4.2 on 2024-10-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_patientprofile_health_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='diet_plan',
            field=models.TextField(default=' '),
        ),
    ]
