# Generated by Django 4.2 on 2024-09-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_created',
            field=models.BooleanField(default=True, verbose_name='profile created'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
