# Generated by Django 4.2 on 2024-12-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctoraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
