# Generated by Django 4.2 on 2024-12-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctorprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='doctorprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='speciality',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
