# Generated by Django 4.2 on 2025-01-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_doctorprofile_age_remove_doctorprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='education',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
