# Generated by Django 4.2 on 2025-01-31 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_appointment_doctorservices_appointmentslot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentpayment',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='appointmentslot',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='doctorservices',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='AppointmentPayment',
        ),
        migrations.DeleteModel(
            name='AppointmentSlot',
        ),
        migrations.DeleteModel(
            name='DoctorServices',
        ),
    ]
