# Generated by Django 4.2 on 2025-01-31 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_appointment_doctorservices_appointmentslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_address', to='doctor.doctoraddress'),
        ),
    ]
