# Generated by Django 4.2 on 2025-02-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_servicemarketting'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'patient'], name='doctor_appo_doctor__6f3dc8_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['doctor', 'status'], name='doctor_appo_doctor__f83c51_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentslot',
            index=models.Index(fields=['doctor', 'date'], name='doctor_appo_doctor__8e229c_idx'),
        ),
    ]
