# Generated by Django 4.2 on 2025-03-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_appointment_doctor_appo_doctor__6f3dc8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemarketting',
            name='customer_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
