# Generated by Django 4.2 on 2025-03-16 16:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_alter_appointment_appointment_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftedAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doctor_message', models.TextField(blank=True, null=True)),
                ('patient_accepted', models.BooleanField(default=False)),
                ('patient_message', models.TextField(blank=True, null=True)),
                ('event_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.appointment')),
                ('shifted_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.appointmentslot')),
            ],
        ),
    ]
